### ISSUE TITLE
Default Image Fill Type is not correct

### ISSUE THREAD

**Issue by submetu** [smartface/sf-extension-zoomable-imageview#2]
On Android, we need to provide a fill type. Otherwise the image looks very small.
On iOS, if we dont give the fill type, the image floats around.

I gave the filltype in the following way in it worked:
```
    let myZoomableImageView = new ZoomableImageView({
      width: 200,
      height: 200,
      imageFillType: ImageView.FillType.ASPECTFILL
    });
```

Maybe we can have this ON by default

**Comment by furkanarabaci** [comment]
We no longer delete imageFillType, therefore whatever filltype given, will be used.
